[project]
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
name = "tdd-lab"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
coverage = "coverage"
format = "ruff format"
lint = "ruff check"
task2 = "python ./TDD_lab_student/Task2_unittest.py"
task1 = "python ./TDD_lab_student/Task1_Unittest_rover.py"

[dependencies]
python = ">=3.13.2,<3.14"
coverage = ">=7.6.12,<8"
ruff = ">=0.9.6,<0.10"
