[project]
channels = ["conda-forge"]
name = "tdd-lab"
platforms = ["win-64"]

[tasks]
format = "ruff format"
lint = "ruff check"
task2 = "python ./TDD_lab_student/Task2_unittest.py"
task1 = "python ./TDD_lab_student/Task1_Unittest_rover.py"
coverage = "coverage run -m unittest ./TDD_lab_student/*; coverage report"

[tasks.report]
cmd = "coverage html"
depends-on = ["coverage"]

[dependencies]
python = ">=3.13.2,<3.14"
coverage = ">=7.6.12,<8"
ruff = ">=0.9.6,<0.10"
