[project]
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
name = "tdd-lab"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
coverage = "coverage"

[dependencies]
python = ">=3.13.2,<3.14"
coverage = ">=7.6.12,<8"
